apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
namespace: flask-app
resources:
  - namespace.yml
  - secrets.yml
  - ../../configmap.yml
  - ../../deployment.yml
  - ../../service.yml

commonLabels:
  app: my-web-app