---
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
stringData:
  uri: postgresql://`echo ${mydbusr}`:`echo ${mydbpasswd}`@`echo ${dburl}`:`echo ${dbport}`/`echo ${dbname}`
  # POSTGRES_USER: `echo ${mydbusr}` # DBUSERENV
  # POSTGRES_PASSWORD: `echo ${mydbpswd}` # DBPASSWORDENV
...

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
type: kubernetes.io/tls
data:
  tls.cert: `cat tls.crt.base64` # <base64 encoded certificate>
  tls.key: `cat tls.key.base64` # <base64 encoded key>
...